services:
  vanadium-builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vanadium-builder
    # These are the bare minimum to build Vanadium
    environment:
      - VANADIUM_MANIFEST=114.0.5735.131.0
    volumes:
      - ./grapheneos-vanadium/:/opt/build/vanadium
